"use client"
import Messages from "@/components/responser"
import './globals.css'
import { Inter } from 'next/font/google'
import { Provider, useSelector } from "react-redux";
import { store, persistor } from "../redux";

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider store={store}>
<Childern>{children}</Childern>
      </Provider>
      </body>
    </html>
  )
}

export function Childern({ children }) {
  const { open, message, vertical, horizontal, severity, autoHideDuration } =useSelector((state) => state.Notification);
 return <>
      <Messages
        open={open}
        message={message}
        vertical={vertical}
        horizontal={horizontal}
        severity={severity}
        autoHideDuration={autoHideDuration}
      />
      {children}
 </>
}